blank_issues_enabled: false
contact_links:
  - name: Question & Suggestions
    url: https://discord.com/invite/EXreXqJCdx
    about: Do not use the issue tracker as suggestions or questions! Do it on the Discord server instead.